### ISSUE TITLE
Getting 404 Recently 

### ISSUE THREAD

**Issue by ddh4r4m** [sergeykhliustin/BazelPods#76]
When running bazel run @bazelpods//:bazelpods -- --src $PWD

```
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dharamdhurandhar/1ba2c15dce626bae860ed76d517179b5/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: Download from https://github.com/sergeykhliustin/BazelPods/releases/download/refs/tags/0.10.0/release.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'bazelpods':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dharamdhurandhar/1ba2c15dce626bae860ed76d517179b5/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/sergeykhliustin/BazelPods/releases/download/refs/tags/0.10.0/release.tar.gz] to /private/var/tmp/_bazel_dharamdhurandhar/1ba2c15dce626bae860ed76d517179b5/external/bazelpods/temp11471496726281356101/release.tar.gz: GET returned 404 Not Found
ERROR: /Users/dharamdhurandhar/Developer/xcodeSample/WORKSPACE:44:13: fetching http_archive rule //external:bazelpods: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dharamdhurandhar/1ba2c15dce626bae860ed76d517179b5/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/sergeykhliustin/BazelPods/releases/download/refs/tags/0.10.0/release.tar.gz] to /private/var/tmp/_bazel_dharamdhurandhar/1ba2c15dce626bae860ed76d517179b5/external/bazelpods/temp11471496726281356101/release.tar.gz: GET returned 404 Not Found
ERROR: Error computing the main repository mapping: no such package '@bazelpods//': java.io.IOException: Error downloading [https://github.com/sergeykhliustin/BazelPods/releases/download/refs/tags/0.10.0/release.tar.gz] to /private/var/tmp/_bazel_dharamdhurandhar/1ba2c15dce626bae860ed76d517179b5/external/bazelpods/temp11471496726281356101/release.tar.gz: GET returned 404 Not Found
```

**Comment by ddh4r4m** [comment]
This Fixed the issue, @sergeykhliustin There might be a need to update the Release notes
```

http_archive(
    name = "bazelpods",
    sha256 = "0b3c51f3347ee1fd977e3491387eabf1381e076850024a9e791ed23895184adf",
    url = "https://github.com/sergeykhliustin/BazelPods/archive/refs/tags/0.10.0.tar.gz"
)

load("@bazelpods//:repositories.bzl", "bazelpods_dependencies")

bazelpods_dependencies()
```

**Comment by sergeykhliustin** [comment]
hey @ddh4r4m , thanks for your report.
seems like release script broken, will check

**Comment by sergeykhliustin** [comment]
@ddh4r4m 
correct snippet will be
```
http_archive(
    name = "bazelpods",
    sha256 = "b1e161f585dc1fc8f0fc1e1238aa681d5caa538aa0061e652510f3d0323318c1",
    url = "https://github.com/sergeykhliustin/BazelPods/releases/download/0.10.0/release.tar.gz"
)

load("@bazelpods//:repositories.bzl", "bazelpods_dependencies")

bazelpods_dependencies()
```

release notes updated
